## Análisis de Datos con Pandas: Carga y Exploración de DataFrames

Fuentes de datasets
https://www.kaggle.com/

In [2]:
import kagglehub

c:\Users\Alejandro\OneDrive\SecondBrain\Estudio\PLATZI\Escuela de Python\Curso de Python para Ciencia de Datos\CursoCienciaDatos\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
import pandas as pd

## Cargar datos
path = 'Online_Retail.csv'
retail_data = pd.read_csv(path, encoding='ISO-8859-1')
print(type(retail_data))
print(retail_data)

<class 'pandas.DataFrame'>
       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

          InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/10 8:26       2.55     17850.0  United Kingdom
1        12/1/10 8:26       3.39     17850.0  United Kingdom
2        12/1/10 8:26       2.75     17850.0  United Kingdom
3        12/1/10 8:26       3.39     17850.0  United Kingdom
4        12/1/10 8:26       3.39     17850.0  United Kingdom
...               ...        ...         ...             ...
541904  12/9/11 12:50       0.85     12680.0          France
541905  12/9/11 12:50       2.10     12680.0          France
541906  12/9/11 12:50       4.15     12680.0          France
541907  12/9/11 12:50       4.15     12680.0          France
541908  12/9/11 12:50       4.95     12680.0          France

[541909 rows x 8 columns]

# Creación de DataFrames con Pandas en Python

In [4]:
import pandas as pd

## Cargar datos
path = 'Online_Retail.csv'
sales_data = pd.read_csv(path, encoding='ISO-8859-1')
print(retail_data.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom

Creación de un dataframe desde un array  de numpy

In [5]:
import numpy as np 

data = np.array([[1,2,3], [4,5,6], [7,8,9]])
##Creación desde un array de numpy
dt_from_array = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(dt_from_array)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

Creación de un dataframe desde una lista

In [6]:
data = [[1,'jhon', 22], [2, 'Anna', 24]]

##Creación desde una lista
df_from_list = pd.DataFrame(data, columns =['ID', 'Nombre', 'edad'])
print(df_from_list)

   ID Nombre  edad
0   1   jhon    22
1   2   Anna    24

Creación de un dataframe desde una lista de diccionarios

In [7]:
data = [
    {'ID': 1, 'Name': 'Jhon', 'Age': 22},
    {'ID': 2, 'Name': 'Alex', 'Age': 34}
    ]
##Creación desde una lista de diccionarios
dt_from_dict_list = pd.DataFrame(data)
print(dt_from_dict_list)

   ID  Name  Age
0   1  Jhon   22
1   2  Alex   34

Creación de un Dataframe desde un diccionario.

In [8]:
data = {'ID': [1,2,3], 
    'Name': ['Jhon', 'Anna', 'Mike'],
    'Age': [22, 24, 21]
}
## Creación de un DataFrame desde un diccionario
dt_frame_dict = pd.DataFrame(data)
print(dt_frame_dict)

   ID  Name  Age
0   1  Jhon   22
1   2  Anna   24
2   3  Mike   21

Creación de una dataframe media un diccionario de series.

In [9]:
data = {
    'ID': pd.Series([1, 2, 3]),
    'Name': pd.Series(['Jhon', 'Anna', 'Mike']),
    'Age': pd.Series([22, 24, 21])
}

## Creación desde un Dataframe desde diccionarios de Series 

dt_frame_dict = pd.DataFrame(data)
print(dt_frame_dict)

   ID  Name  Age
0   1  Jhon   22
1   2  Anna   24
2   3  Mike   21

## Análisis de Datos con Pandas: Series y DataFrames en RetailData

Obtención del nombre de laas columnas

In [10]:
columns_names = retail_data.columns
print(columns_names)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

Obtención de numeros de columanas y filas

In [11]:
# numero de columnas y filas
num_rows, num_columns  = retail_data.shape
print('Numero de filas', num_rows)
print('Numero de columnas', num_columns)

Numero de filas 541909
Numero de columnas 8

Obtención de datos de caantidad

In [12]:
daily_sales = retail_data['Quantity']
unit_price_retail = retail_data['UnitPrice']

print(daily_sales)
print(unit_price_retail)

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64
0         2.55
1         3.39
2         2.75
3         3.39
4         3.39
          ...
541904    0.85
541905    2.10
541906    4.15
541907    4.15
541908    4.95
Name: UnitPrice, Length: 541909, dtype: float64

Resumen estadítico de los datos

In [13]:
summary = retail_data.describe()
print(summary)

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [14]:
## Media
daily_mean_value = daily_sales.mean()
upr_mean = unit_price_retail.mean()

print('La media quantity es:', daily_mean_value)
print('La media unit price es:', upr_mean)

## Mediana
media_value = daily_sales.median()
upr_media = unit_price_retail.median()

print('La mediana quantity es:', media_value)
print('La median unit price es:', upr_media)

##Suma total de las columna
sum_value = daily_sales.sum()
upr_sum = unit_price_retail.sum()
print('La suma total quantity es:', sum_value)
print('La suma total unit price es:', upr_sum)

##Contar el total de valores
count_values = daily_sales.count()
upr_count = unit_price_retail.count() 

print('Valores contados quantity:', count_values)
print('Valores contados unit price:', upr_count)

La media quantity es: 9.55224954743324
La media unit price es: 4.611113626088514
La mediana quantity es: 3.0
La median unit price es: 2.08

La suma total quantity es: 5176450
La suma total unit price es: 2498803.9740000004
Valores contados quantity: 541909
Valores contados unit price: 541909

In [15]:
#Información de cabeceras
retail_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

## Selección de Datos en Pandas: Uso de iLoc y loc

In [16]:
#Usando iloc
first_row = retail_data.iloc[0]
print(first_row)

InvoiceNo                                  536365
StockCode                                  85123A
Description    WHITE HANGING HEART T-LIGHT HOLDER
Quantity                                        6
InvoiceDate                          12/1/10 8:26
UnitPrice                                    2.55
CustomerID                                17850.0
Country                            United Kingdom
Name: 0, dtype: object

In [17]:
first_row = retail_data.iloc[:7]
print(first_row)

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
5    536365     22752         SET 7 BABUSHKA NESTING BOXES         2
6    536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom
5  12/1/10 8:26       7.65     17850.0  United Kingdom
6  12/1/10 8:26       4.25     17850.0  United Kingdom

In [18]:
subset = retail_data.iloc[:5,:3]
print(subset)

  InvoiceNo StockCode                          Description
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER
1    536365     71053                  WHITE METAL LANTERN
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.

In [19]:
row_index_3 = retail_data.loc[3]
print(row_index_3)

InvoiceNo                                   536365
StockCode                                   84029G
Description    KNITTED UNION FLAG HOT WATER BOTTLE
Quantity                                         6
InvoiceDate                           12/1/10 8:26
UnitPrice                                     3.39
CustomerID                                 17850.0
Country                             United Kingdom
Name: 3, dtype: object

In [20]:
row_index_0_to_4 = retail_data.loc[0:4]
print(row_index_0_to_4)

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom

In [21]:
quantity_column = retail_data.loc[:,'Quantity']
print(quantity_column)

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64

In [22]:
quantity_unitprices_column = retail_data.loc[:,['Quantity', 'UnitPrice']]
print("quantity    unit prices")
print(quantity_column)

quantity    unit prices
0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64

# Manejo de Datos Faltantes en Pandas: Identificación y Tratamiento

In [23]:
#Enocntrar valores faltantes
missing_data = retail_data.isna()
print(missing_data)

        InvoiceNo  StockCode  Description  Quantity  InvoiceDate  UnitPrice  \
0           False      False        False     False        False      False
1           False      False        False     False        False      False
2           False      False        False     False        False      False
3           False      False        False     False        False      False
4           False      False        False     False        False      False
...           ...        ...          ...       ...          ...        ...
541904      False      False        False     False        False      False
541905      False      False        False     False        False      False
541906      False      False        False     False        False      False
541907      False      False        False     False        False      False
541908      False      False        False     False        False      False

        CustomerID  Country
0            False    False
1            False    False
2            False    False
3            False    False
4            False    False
...            ...      ...
541904       False    False
541905       False    False
541906       False    False
541907       False    False
541908       False    False

[541909 rows x 8 columns]

In [24]:
## Obtener cantidad de datos faltantes en cada columna.
missing_data_count = retail_data.isna().sum()
print('Conteo de datos faltantes por conlumna: \n', missing_data_count)

Conteo de datos faltantes por conlumna:
 InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [25]:
#Se filtran o quitan las filas con datos faltantes
no_missing_rows = retail_data.dropna()
print(no_missing_rows)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

          InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/10 8:26       2.55     17850.0  United Kingdom
1        12/1/10 8:26       3.39     17850.0  United Kingdom
2        12/1/10 8:26       2.75     17850.0  United Kingdom
3        12/1/10 8:26       3.39     17850.0  United Kingdom
4        12/1/10 8:26       3.39     17850.0  United Kingdom
...               ...        ...         ...             ...
541904  12/9/11 12:50       0.85     12680.0          France
541905  12/9/11 12:50       2.10     12680.0          France
541906  12/9/11 12:50       4.15     12680.0          France
541907  12/9/11 12:50       4.15     12680.0          France
541908  12/9/11 12:50       4.95     12680.0          France

[406829 rows x 8 columns]

In [26]:
#Se filtran o quitan las columnas con datos faltantes
no_missing_columns = retail_data.dropna(axis=1)
print(no_missing_columns)

       InvoiceNo StockCode  Quantity    InvoiceDate  UnitPrice         Country
0         536365    85123A         6   12/1/10 8:26       2.55  United Kingdom
1         536365     71053         6   12/1/10 8:26       3.39  United Kingdom
2         536365    84406B         8   12/1/10 8:26       2.75  United Kingdom
3         536365    84029G         6   12/1/10 8:26       3.39  United Kingdom
4         536365    84029E         6   12/1/10 8:26       3.39  United Kingdom
...          ...       ...       ...            ...        ...             ...
541904    581587     22613        12  12/9/11 12:50       0.85          France
541905    581587     22899         6  12/9/11 12:50       2.10          France
541906    581587     23254         4  12/9/11 12:50       4.15          France
541907    581587     23255         4  12/9/11 12:50       4.15          France
541908    581587     22138         3  12/9/11 12:50       4.95          France

[541909 rows x 6 columns]

In [27]:
## Reemplaza el dato faltante con cero.
retail_data_filter_zeros = retail_data.fillna(0)
retail_data_filter_zeros_count = retail_data_filter_zeros.isna().sum()
print(retail_data_filter_zeros_count)

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [28]:
## Reemplaza el dato faltante con la media aritmetica
mean_unit_prices = retail_data['UnitPrice'].mean()
retail_data_filled_mean = retail_data['UnitPrice'].fillna(mean_unit_prices)
print(retail_data_filled_mean)

0         2.55
1         3.39
2         2.75
3         3.39
4         3.39
          ...
541904    0.85
541905    2.10
541906    4.15
541907    4.15
541908    4.95
Name: UnitPrice, Length: 541909, dtype: float64

# Transformaciones y Manipulación de Datos con Pandas en Python

In [29]:
import pandas as pd
path = 'Online_Retail.csv'
df = pd.read_csv(path, encoding='ISO-8859-1')
## Cálculo de Precio Total.
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice
0  12/1/10 8:26       2.55     17850.0  United Kingdom       15.30
1  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34
2  12/1/10 8:26       2.75     17850.0  United Kingdom       22.00
3  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34
4  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34

In [30]:
## Filtrar valores mayores a 16
df['HighValue'] = df['TotalPrice'] > 16
print(df['HighValue'].head(15))

0     False
1      True
2      True
3      True
4      True
5     False
6      True
7     False
8     False
9      True
10    False
11    False
12     True
13    False
14     True
Name: HighValue, dtype: bool

In [31]:
## Da información de las conlumnas 
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
 8   TotalPrice   541909 non-null  float64
 9   HighValue    541909 non-null  bool
dtypes: bool(1), float64(3), int64(1), str(5)
memory usage: 37.7 MB
None

In [32]:
## Transfoma el tipo de dato de una columna.
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
print(df.info())

C:\Users\Alejandro\AppData\Local\Temp\ipykernel_7296\958132825.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
 8   TotalPrice   541909 non-null  float64
 9   HighValue    541909 non-null  bool
dtypes: bool(1), datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 37.7 MB
None

In [33]:
##  Aplicar función lambda
df['DiscountedPrice'] = df['UnitPrice'].apply(lambda x: x*0.9)
print(df.head(3))

  InvoiceNo StockCode                         Description  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                 WHITE METAL LANTERN         6
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00

   HighValue  DiscountedPrice
0      False            2.295
1       True            3.051
2       True            2.475

In [34]:
## Clasificación de precios unitarios
def categorize_price(price): 
    if price >= 4:
        return 'High'
    elif 2 <= price < 4:
        return 'Medium'
    else:
        return 'Low'
    
df['PriceCategory'] = df['UnitPrice'].apply(categorize_price)

print( df.loc[20:40,['UnitPrice', 'PriceCategory'] ] )

    UnitPrice PriceCategory
20       7.95          High
21       4.25          High
22       4.95          High
23       4.95          High
24       4.95          High
25       5.95          High
26       3.75        Medium
27       3.75        Medium
28       3.75        Medium
29       0.85           Low
30       0.65           Low
31       0.85           Low
32       1.25           Low
33       2.95        Medium
34       2.95        Medium
35       1.95           Low
36       1.95           Low
37       1.95           Low
38       0.85           Low
39       1.65           Low
40       2.95        Medium

# Análisis de Ventas con Pandas: Agrupaciones y Estadísticas

In [35]:
## Groupby - agrupar paises y cuenta 
country_count= df['Country'].value_counts()
print(country_count)

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [36]:
## Agrupa los paises y suma la cantidad en este caso las ventas.
country_group = df.groupby('Country')['Quantity'].sum()
print(country_group)

Country
Australia                 83653
Austria                    4827
Bahrain                     260
Belgium                   23152
Brazil                      356
Canada                     2763
Channel Islands            9479
Cyprus                     6317
Czech Republic              592
Denmark                    8188
EIRE                     142637
European Community          497
Finland                   10666
France                   110480
Germany                  117448
Greece                     1556
Hong Kong                  4769
Iceland                    2458
Israel                     4353
Italy                      7999
Japan                     25218
Lebanon                     386
Lithuania                   652
Malta                       944
Netherlands              200128
Norway                    19247
Poland                     3653
Portugal                  16180
RSA                         352
Saudi Arabia                 75
Singapore                  5234
Spain                     26824
Sweden                    35637
Switzerland               30325
USA                        1034
United Arab Emirates        982
United Kingdom          4263829
Unspecified                3300
Name: Quantity, dtype: int64

In [37]:
## Media y suma del precio unitario
country_stats = df.groupby('Country')['UnitPrice'].agg(['mean', 'sum']) 
print(country_stats)

                            mean          sum
Country
Australia               3.220612     4054.750
Austria                 4.243192     1701.520
Bahrain                 4.556316       86.570
Belgium                 3.644335     7540.130
Brazil                  4.456250      142.600
Canada                  6.030331      910.580
Channel Islands         4.932124     3738.550
Cyprus                  6.302363     3920.070
Czech Republic          2.938333       88.150
Denmark                 3.256941     1266.950
EIRE                    5.911077    48447.190
European Community      4.820492      294.050
Finland                 5.448705     3786.850
France                  5.028864    43031.990
Germany                 3.966930    37666.000
Greece                  4.885548      713.290
Hong Kong              42.505208    12241.500
Iceland                 2.644011      481.210
Israel                  3.633131     1079.040
Italy                   4.831121     3879.390
Japan                   2.276145      814.860
Lebanon                 5.387556      242.440
Lithuania               2.841143       99.440
Malta                   5.244173      666.010
Netherlands             2.738317     6492.550
Norway                  6.012026     6529.060
Poland                  4.170880     1422.270
Portugal                8.582976    13037.540
RSA                     4.277586      248.100
Saudi Arabia            2.411000       24.110
Singapore             109.645808    25108.890
Spain                   4.987544    12633.450
Sweden                  3.910887     1806.830
Switzerland             3.403442     6813.690
USA                     2.216426      644.980
United Arab Emirates    3.380735      229.890
United Kingdom          4.532422  2245715.474
Unspecified             2.699574     1204.010

In [38]:
## Stock de compras
country_stock_group = df.groupby(['Country', 'StockCode'])['Quantity'].sum()
print(country_stock_group)

Country      StockCode
Australia    15036        600
             15056BL        3
             16161P       400
             16169E        25
             20665          6
                         ...
Unspecified  85180A         2
             85180B         1
             85212         12
             85213         12
             85227         10
Name: Quantity, Length: 19839, dtype: int64

In [39]:
def total_revenue(group):
    return (group['Quantity'] * group['UnitPrice']).sum()

revenue_per_count = df.groupby('Country').apply(total_revenue)
print(revenue_per_count)

Country
Australia                137077.270
Austria                   10154.320
Bahrain                     548.400
Belgium                   40910.960
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20086.290
Cyprus                    12946.290
Czech Republic              707.720
Denmark                   18768.140
EIRE                     263276.820
European Community         1291.750
Finland                   22326.740
France                   197403.900
Germany                  221698.210
Greece                     4710.520
Hong Kong                 10117.040
Iceland                    4310.000
Israel                     7907.820
Italy                     16890.510
Japan                     35340.620
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2505.470
Netherlands              284661.540
Norway                    35163.460
Poland                     7213.140
Portugal                  29367.020
RSA                        1002.310
Saudi Arabia                131.170
Singapore                  9120.390
Spain                     54774.580
Sweden                    36595.910
Switzerland               56385.350
USA                        1730.920
United Arab Emirates       1902.280
United Kingdom          8187806.364
Unspecified                4749.790
dtype: float64

In [40]:
#Top 3 de mejores paises en ventas
top_3_best = revenue_per_count.sort_values(ascending=False)
top_3_worst = revenue_per_count.sort_values(ascending=True)
print("Top 3 peores: \n", top_3_worst.head(3))
print("Top 3 mejores: \n", top_3_best.head(3))

Top 3 peores:
 Country
Saudi Arabia      131.17
Bahrain           548.40
Czech Republic    707.72
dtype: float64
Top 3 mejores:
 Country
United Kingdom    8187806.364
Netherlands        284661.540
EIRE               263276.820
dtype: float64

## Filtrado de Datos en Pandas para Análisis Efectivo

In [41]:
import pandas as pd

## Leer el dataset de ventas desde un archivoCSV
file_path = "./Online_Retail.csv"
sales_data = pd.read_csv(file_path, encoding='ISO-8859-1')

## Convertir la columna 'InvoiceDate'  a tipo datetime
sales_data['InvoiceDate'] = pd.to_datetime(sales_data['InvoiceDate'])

## Eliminar filas con valores faltantes en la columnas críticas
sales_data.dropna(subset=['CustomerID', 'InvoiceDate'], inplace=True)

## Crear una nueva columna 'TotalPrice'
sales_data['TotalPrice'] = sales_data['Quantity'] * sales_data['UnitPrice']

print(sales_data.head())

C:\Users\Alejandro\AppData\Local\Temp\ipykernel_7296\3185045893.py:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales_data['InvoiceDate'] = pd.to_datetime(sales_data['InvoiceDate'])

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34

In [42]:
## Filtrar ventas en el reino unido.
uk_sales = sales_data[sales_data['Country'] == 'United Kingdom']
print(uk_sales)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541889    581585     22466       FAIRY TALE COTTAGE NIGHT LIGHT        12
541890    581586     22061  LARGE CAKE STAND  HANGING STRAWBERY         8
541891    581586     23275     SET OF 3 HANGING OWLS OLLIE BEAK        24
541892    581586     21217        RED RETROSPOT ROUND CAKE TINS        24
541893    581586     20685                DOORMAT RED RETROSPOT        10

               InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
...                    ...        ...         ...             ...         ...
541889 2011-12-09 12:31:00       1.95     15804.0  United Kingdom       23.40
541890 2011-12-09 12:49:00       2.95     13113.0  United Kingdom       23.60
541891 2011-12-09 12:49:00       1.25     13113.0  United Kingdom       30.00
541892 2011-12-09 12:49:00       8.95     13113.0  United Kingdom      214.80
541893 2011-12-09 12:49:00       7.08     13113.0  United Kingdom       70.80

[361878 rows x 9 columns]

In [43]:
##Filtrar ventas altas (mayores a 10)
high_quantity_sales = sales_data[sales_data['Quantity'] > 10 ]
print(high_quantity_sales)

       InvoiceNo StockCode                      Description  Quantity  \
9         536367     84879    ASSORTED COLOUR BIRD ORNAMENT        32
26        536370     22728        ALARM CLOCK BAKELIKE PINK        24
27        536370     22727        ALARM CLOCK BAKELIKE RED         24
28        536370     22726       ALARM CLOCK BAKELIKE GREEN        12
29        536370     21724  PANDA AND BUNNIES STICKER SHEET        12
...          ...       ...                              ...       ...
541894    581587     22631         CIRCUS PARADE LUNCH BOX         12
541895    581587     22556   PLASTERS IN TIN CIRCUS PARADE         12
541896    581587     22555        PLASTERS IN TIN STRONGMAN        12
541902    581587     22629              SPACEBOY LUNCH BOX         12
541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12

               InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice
9      2010-12-01 08:34:00       1.69     13047.0  United Kingdom       54.08
26     2010-12-01 08:45:00       3.75     12583.0          France       90.00
27     2010-12-01 08:45:00       3.75     12583.0          France       90.00
28     2010-12-01 08:45:00       3.75     12583.0          France       45.00
29     2010-12-01 08:45:00       0.85     12583.0          France       10.20
...                    ...        ...         ...             ...         ...
541894 2011-12-09 12:50:00       1.95     12680.0          France       23.40
541895 2011-12-09 12:50:00       1.65     12680.0          France       19.80
541896 2011-12-09 12:50:00       1.65     12680.0          France       19.80
541902 2011-12-09 12:50:00       1.95     12680.0          France       23.40
541904 2011-12-09 12:50:00       0.85     12680.0          France       10.20

[126312 rows x 9 columns]

In [44]:
## Filtrado de ventas por valor y pais especifico.
uk_kingdom_quantity_sales = sales_data[ (sales_data['Country']=='United Kingdom')&
                                        (sales_data['Quantity'] > 20) ]

print(uk_kingdom_quantity_sales)

       InvoiceNo StockCode                         Description  Quantity  \
9         536367     84879       ASSORTED COLOUR BIRD ORNAMENT        32
46        536371     22086     PAPER CHAIN KIT 50'S CHRISTMAS         80
65        536374     21258          VICTORIAN SEWING BOX LARGE        32
82        536376     22114   HOT WATER BOTTLE TEA AND SYMPATHY        48
83        536376     21733    RED HANGING HEART T-LIGHT HOLDER        64
...          ...       ...                                 ...       ...
541876    581585     84945  MULTI COLOUR SILVER T-LIGHT HOLDER        24
541882    581585     21916     SET 12 RETRO WHITE CHALK STICKS        24
541883    581585     84692         BOX OF 24 COCKTAIL PARASOLS        25
541891    581586     23275    SET OF 3 HANGING OWLS OLLIE BEAK        24
541892    581586     21217       RED RETROSPOT ROUND CAKE TINS        24

               InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice
9      2010-12-01 08:34:00       1.69     13047.0  United Kingdom       54.08
46     2010-12-01 09:00:00       2.55     13748.0  United Kingdom      204.00
65     2010-12-01 09:09:00      10.95     15100.0  United Kingdom      350.40
82     2010-12-01 09:32:00       3.45     15291.0  United Kingdom      165.60
83     2010-12-01 09:32:00       2.55     15291.0  United Kingdom      163.20
...                    ...        ...         ...             ...         ...
541876 2011-12-09 12:31:00       0.85     15804.0  United Kingdom       20.40
541882 2011-12-09 12:31:00       0.42     15804.0  United Kingdom       10.08
541883 2011-12-09 12:31:00       0.42     15804.0  United Kingdom       10.50
541891 2011-12-09 12:49:00       1.25     13113.0  United Kingdom       30.00
541892 2011-12-09 12:49:00       8.95     13113.0  United Kingdom      214.80

[44541 rows x 9 columns]

In [45]:
## Filtrado de información por año 
sales_2011 = sales_data[sales_data['InvoiceDate'].dt.year == 2011]
print(sales_2011)

       InvoiceNo StockCode                      Description  Quantity  \
42481     539993     22386          JUMBO BAG PINK POLKADOT        10
42482     539993     21499               BLUE POLKADOT WRAP        25
42483     539993     21498              RED RETROSPOT WRAP         25
42484     539993     22379         RECYCLING BAG RETROSPOT          5
42485     539993     20718        RED RETROSPOT SHOPPER BAG        10
...          ...       ...                              ...       ...
541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899     CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138    BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice
42481  2011-01-04 10:00:00       1.95     13313.0  United Kingdom       19.50
42482  2011-01-04 10:00:00       0.42     13313.0  United Kingdom       10.50
42483  2011-01-04 10:00:00       0.42     13313.0  United Kingdom       10.50
42484  2011-01-04 10:00:00       2.10     13313.0  United Kingdom       10.50
42485  2011-01-04 10:00:00       1.25     13313.0  United Kingdom       12.50
...                    ...        ...         ...             ...         ...
541904 2011-12-09 12:50:00       0.85     12680.0          France       10.20
541905 2011-12-09 12:50:00       2.10     12680.0          France       12.60
541906 2011-12-09 12:50:00       4.15     12680.0          France       16.60
541907 2011-12-09 12:50:00       4.15     12680.0          France       16.60
541908 2011-12-09 12:50:00       4.95     12680.0          France       14.85

[379979 rows x 9 columns]

In [46]:
sales_dec_2010 = sales_data[(sales_data['InvoiceDate'].dt.year == 2010) &
                            (sales_data['InvoiceDate'].dt.month == 12)]
print(sales_dec_2010)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1        536365     71053                  WHITE METAL LANTERN         6
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...         ...       ...                                  ...       ...
42448    539988     84380    SET OF 3 BUTTERFLY COOKIE CUTTERS         1
42449    539988    84849D                HOT BATHS SOAP HOLDER         1
42450    539988    84849B               FAIRY SOAP SOAP HOLDER         1
42451    539988     22854          CREAM SWEETHEART EGG HOLDER         2
42452    539988    47559B                  TEA TIME OVEN GLOVE         2

              InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice
0     2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2     2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
...                   ...        ...         ...             ...         ...
42448 2010-12-23 16:06:00       1.25     18116.0  United Kingdom        1.25
42449 2010-12-23 16:06:00       1.69     18116.0  United Kingdom        1.69
42450 2010-12-23 16:06:00       1.69     18116.0  United Kingdom        1.69
42451 2010-12-23 16:06:00       4.95     18116.0  United Kingdom        9.90
42452 2010-12-23 16:06:00       1.25     18116.0  United Kingdom        2.50

[26850 rows x 9 columns]

## Creación y manejo de Pivot Tables en pandas

In [47]:
pivot_table = pd.pivot_table(sales_data, values = 'Quantity', index='Country',
                             columns='StockCode', aggfunc='sum')
print(pivot_table)

StockCode             10002  10080  10120  10123C  10124A  10124G  10125  \
Country
Australia               NaN    NaN    NaN     NaN     NaN     NaN    NaN
Austria                 NaN    NaN    NaN     NaN     NaN     NaN    NaN
Bahrain                 NaN    NaN    NaN     NaN     NaN     NaN    NaN
Belgium                 NaN    NaN    NaN     NaN     NaN     NaN    NaN
Brazil                  NaN    NaN    NaN     NaN     NaN     NaN    NaN
Canada                  NaN    NaN    NaN     NaN     NaN     NaN    NaN
Channel Islands         NaN    NaN    NaN     NaN     NaN     NaN    NaN
Cyprus                  NaN    NaN    NaN     NaN     NaN     NaN    NaN
Czech Republic          NaN    NaN    NaN     NaN     NaN     NaN    NaN
Denmark                 NaN    NaN    NaN     NaN     NaN     NaN    NaN
EIRE                   12.0    NaN    NaN     NaN     NaN     NaN    NaN
European Community      NaN    NaN    NaN     NaN     NaN     NaN    NaN
Finland                 NaN    NaN    NaN     NaN     NaN     NaN    NaN
France                372.0    NaN   10.0     NaN     NaN     NaN  470.0
Germany                 1.0    NaN    NaN     NaN     NaN     NaN  120.0
Greece                  NaN    NaN    NaN     NaN     NaN     NaN    NaN
Iceland                 NaN    NaN    NaN     NaN     NaN     NaN    NaN
Israel                  NaN    NaN    NaN     NaN     NaN     NaN    NaN
Italy                   NaN    NaN    NaN     NaN     NaN     NaN    NaN
Japan                   1.0    NaN    NaN     NaN     NaN     NaN    NaN
Lebanon                 NaN    NaN    NaN     NaN     NaN     NaN    NaN
Lithuania               NaN    NaN    NaN     NaN     NaN     NaN    NaN
Malta                   NaN    NaN    NaN     NaN     NaN     NaN    NaN
Netherlands             NaN    NaN    NaN     NaN     NaN     NaN    NaN
Norway                  NaN    NaN    NaN     NaN     NaN     NaN    NaN
Poland                  NaN    NaN    NaN     NaN     NaN     NaN    NaN
Portugal                NaN    NaN    NaN     NaN     NaN     NaN    NaN
RSA                     NaN    NaN    NaN     NaN     NaN     NaN    NaN
Saudi Arabia            NaN    NaN    NaN     NaN     NaN     NaN    NaN
Singapore               NaN    NaN    NaN     NaN     NaN     NaN    NaN
Spain                  24.0    NaN    NaN     NaN     NaN     NaN    NaN
Sweden                  NaN    NaN    NaN     NaN     NaN     NaN    NaN
Switzerland            12.0    NaN    NaN     NaN     NaN     NaN   20.0
USA                     NaN    NaN    NaN     NaN     NaN     NaN    NaN
United Arab Emirates    NaN    NaN    NaN     NaN     NaN     NaN    NaN
United Kingdom        401.0  291.0  183.0     5.0    16.0    17.0  616.0
Unspecified             NaN    NaN    NaN     NaN     NaN     NaN    NaN

StockCode              10133   10135  11001  ...  90214Y  90214Z  \
Country                                      ...
Australia                NaN     NaN    NaN  ...     NaN     NaN
Austria                  NaN     NaN    NaN  ...     NaN     NaN
Bahrain                  NaN     NaN    NaN  ...     NaN     NaN
Belgium                  NaN     NaN    NaN  ...     NaN     NaN
Brazil                   NaN     NaN    NaN  ...     NaN     NaN
Canada                  40.0    20.0    NaN  ...     NaN     NaN
Channel Islands          NaN     NaN    NaN  ...     NaN     NaN
Cyprus                   NaN     NaN    NaN  ...     NaN     NaN
Czech Republic           NaN     NaN    NaN  ...     NaN     NaN
Denmark                  NaN     NaN    NaN  ...     NaN     NaN
EIRE                    40.0    60.0   48.0  ...     NaN     NaN
European Community       NaN     NaN    NaN  ...     NaN     NaN
Finland                  NaN     NaN    NaN  ...     NaN     NaN
France                   NaN    10.0   16.0  ...     NaN     NaN
Germany                  NaN   200.0   32.0  ...     NaN     NaN
Greece                   NaN     NaN    NaN  ...     NaN     NaN
Iceland                  NaN     NaN    NaN  ...     NaN     NaN
Israel                  20.0     NaN    NaN  ...     NaN     NaN
Italy                    NaN     NaN    NaN  ...     NaN     NaN
Japan                    NaN     NaN    NaN  ...     NaN     NaN
Lebanon                  NaN     NaN    NaN  ...     NaN     NaN
Lithuania                NaN     NaN    NaN  ...     NaN     NaN
Malta                    NaN     NaN    NaN  ...     NaN     NaN
Netherlands              NaN     NaN    NaN  ...     NaN     NaN
Norway                   NaN    10.0   16.0  ...     NaN     NaN
Poland                   NaN     NaN    NaN  ...     NaN     NaN
Portugal                20.0     NaN   16.0  ...     NaN     NaN
RSA                      NaN     NaN    NaN  ...     NaN     NaN
Saudi Arabia             NaN     NaN    NaN  ...     NaN     NaN
Singapore                NaN     NaN    NaN  ...     NaN     NaN
Spain                    NaN     NaN   16.0  ...     NaN     NaN
Sweden                   NaN     NaN    NaN  ...     NaN     NaN
Switzerland             10.0     NaN    NaN  ...     NaN     NaN
USA                      NaN     NaN    NaN  ...     NaN     NaN
United Arab Emirates     NaN     NaN    NaN  ...     NaN     NaN
United Kingdom        2244.0  1637.0  923.0  ...    61.0    12.0
Unspecified              NaN     NaN    NaN  ...     NaN     NaN

StockCode             BANK CHARGES    C2  CRUK       D   DOT       M  PADS  \
Country
Australia                      NaN   NaN   NaN     NaN   NaN     NaN   NaN
Austria                        NaN   NaN   NaN     NaN   NaN     NaN   NaN
Bahrain                        NaN   NaN   NaN     NaN   NaN     NaN   NaN
Belgium                        NaN   NaN   NaN     NaN   NaN     NaN   NaN
Brazil                         NaN   NaN   NaN     NaN   NaN     NaN   NaN
Canada                         NaN   NaN   NaN     NaN   NaN     NaN   NaN
Channel Islands                NaN   3.0   NaN     NaN   NaN     0.0   NaN
Cyprus                         NaN   NaN   NaN     NaN   NaN     0.0   NaN
Czech Republic                 NaN   NaN   NaN     NaN   NaN     NaN   NaN
Denmark                        NaN   NaN   NaN     NaN   NaN     NaN   NaN
EIRE                           NaN  97.0   NaN    -1.0   NaN    -1.0   NaN
European Community             NaN   NaN   NaN     NaN   NaN     NaN   NaN
Finland                        NaN   NaN   NaN     NaN   NaN     2.0   NaN
France                         NaN   3.0   NaN     NaN   NaN   -16.0   NaN
Germany                        NaN   NaN   NaN     NaN   NaN     2.0   NaN
Greece                         NaN   NaN   NaN     NaN   NaN     NaN   NaN
Iceland                        NaN   NaN   NaN     NaN   NaN     NaN   NaN
Israel                         NaN   NaN   NaN     NaN   NaN     NaN   NaN
Italy                          NaN   NaN   NaN    -1.0   NaN    -1.0   NaN
Japan                          NaN   NaN   NaN     NaN   NaN    -3.0   NaN
Lebanon                        NaN   NaN   NaN     NaN   NaN     NaN   NaN
Lithuania                      NaN   NaN   NaN     NaN   NaN     NaN   NaN
Malta                          NaN   NaN   NaN     NaN   NaN     NaN   NaN
Netherlands                    NaN   NaN   NaN    -1.0   NaN  -480.0   NaN
Norway                         NaN   NaN   NaN     NaN   NaN     0.0   NaN
Poland                         NaN   NaN   NaN     NaN   NaN     NaN   NaN
Portugal                       NaN   NaN   NaN     NaN   NaN     1.0   NaN
RSA                            NaN   NaN   NaN     NaN   NaN     1.0   NaN
Saudi Arabia                   NaN   NaN   NaN     NaN   NaN     NaN   NaN
Singapore                      NaN   NaN   NaN     NaN   NaN     0.0   NaN
Spain                          NaN   NaN   NaN     NaN   NaN    -3.0   NaN
Sweden                         NaN   NaN   NaN     NaN   NaN     1.0   NaN
Switzerland                    NaN   NaN   NaN     NaN   NaN     NaN   NaN
USA                            NaN   NaN   NaN     NaN   NaN     NaN   NaN
United Arab Emirates           NaN   NaN   NaN     NaN   NaN     NaN   NaN
United Kingdom                12.0  30.0 -16.0 -1191.0  16.0  3681.0   4.0
Unspecified                    NaN   NaN   NaN     NaN   NaN     NaN   NaN

StockCode               POST
Country
Australia                0.0
Austria                 37.0
Bahrain                  NaN
Belgium                272.0
Brazil                   NaN
Canada                   1.0
Channel Islands          NaN
Cyprus                   1.0
Czech Republic           0.0
Denmark                 41.0
EIRE                     NaN
European Community       9.0
Finland                 89.0
France                 803.0
Germany               1104.0
Greece                   6.0
Iceland                  NaN
Israel                   NaN
Italy                   44.0
Japan                    NaN
Lebanon                  NaN
Lithuania                NaN
Malta                   10.0
Netherlands             99.0
Norway                  57.0
Poland                   9.0
Portugal                97.0
RSA                      NaN
Saudi Arabia             NaN
Singapore                NaN
Spain                  209.0
Sweden                  37.0
Switzerland             97.0
USA                      NaN
United Arab Emirates     1.0
United Kingdom         -21.0
Unspecified              NaN

[37 rows x 3684 columns]

In [48]:
df = pd.DataFrame({
    'A': ['foo', 'bar', 'baz'],
    'B': [1, 2, 3],
    'C': [4, 5, 6]
})

print(df)

     A  B  C
0  foo  1  4
1  bar  2  5
2  baz  3  6

In [49]:
df_stacked = df.stack()
print(df_stacked)

0  A    foo
   B      1
   C      4
1  A    bar
   B      2
   C      5
2  A    baz
   B      3
   C      6
dtype: object

In [50]:
df_unstacked = df_stacked.unstack()
print(df_unstacked)

     A  B  C
0  foo  1  4
1  bar  2  5
2  baz  3  6

## Fusión de DataFrames con Pandas: merge, concat y join

In [51]:
import pandas as pd
# Crear DataFrames de ejemplo
df1 = pd.DataFrame({
    'key':['A', 'B', 'C'],
    'value1': [1, 2, 3]
})

df2 = pd.DataFrame({
    'key': ['B', 'C', 'D'],
    'value2': [ 4, 5, 6 ]
})

print(df1)
print(df2)

  key  value1
0   A       1
1   B       2
2   C       3
  key  value2
0   B       4
1   C       5
2   D       6

In [52]:
inner_merged = pd.merge(df1, df2, on='key', how='inner')
print(inner_merged)

  key  value1  value2
0   B       2       4
1   C       3       5

In [53]:
outer_merged = pd.merge(df1, df2, on='key', how='outer')
print(outer_merged)

  key  value1  value2
0   A     1.0     NaN
1   B     2.0     4.0
2   C     3.0     5.0
3   D     NaN     6.0

In [54]:
left_merged = pd.merge(df1, df2, on='key', how='left')
print(left_merged)
right_merged = pd.merge(df1, df2, on='key', how='right')
print(right_merged)

  key  value1  value2
0   A       1     NaN
1   B       2     4.0
2   C       3     5.0
  key  value1  value2
0   B     2.0       4
1   C     3.0       5
2   D     NaN       6

In [55]:
# Crear DataFrames de ejemplo
df3 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
})
    
df4 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5']
})
    
# Concatenar verticalmente
vertical_concat = pd.concat([df3, df4])
print("Concatenación Vertical:\n", vertical_concat)

Concatenación Vertical:
     A   B
0  A0  B0
1  A1  B1
2  A2  B2
0  A3  B3
1  A4  B4
2  A5  B5

In [56]:
# Concatenar horizontalmente
horizontal_concat = pd.concat([df3, df4], axis=1)
print("Concatenación Horizontal:\n", horizontal_concat)

Concatenación Horizontal:
     A   B   A   B
0  A0  B0  A3  B3
1  A1  B1  A4  B4
2  A2  B2  A5  B5

In [57]:
# Crear DataFrames de ejemplo con índices
df5 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
}, index=['K0', 'K1', 'K2'])

df6 = pd.DataFrame({
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
}, index=['K0', 'K2', 'K3'])

# Realizar un join
joined = df5.join(df6, how='inner')
print("Join con Índice:\n", joined)

Join con Índice:
      A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C1  D1

## Fechas en Pandas: datetime, índice y filtros

In [59]:
import pandas as pd

## Leer el dataset de ventas desde un archivoCSV
file_path = "./Online_Retail.csv"
df = pd.read_csv(file_path, encoding='ISO-8859-1')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [61]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 33.1 MB

In [69]:
df.dropna(subset=['InvoiceDate'], inplace=True)
df.set_index('InvoiceDate', inplace=True)

KeyError: ['InvoiceDate']

In [73]:
df['Year'] = df.index.year
df['Month'] = df.index.month
df['Weekday'] = df.index.weekday
df['Day'] = df.index.day
df['Hour'] = df.index.hour
df['Second'] = df.index.second

print(df['Year'])
print(df['Month'])

InvoiceDate
2010-12-01 08:26:00    2010
2010-12-01 08:26:00    2010
2010-12-01 08:26:00    2010
2010-12-01 08:26:00    2010
2010-12-01 08:26:00    2010
                       ...
2011-12-09 12:50:00    2011
2011-12-09 12:50:00    2011
2011-12-09 12:50:00    2011
2011-12-09 12:50:00    2011
2011-12-09 12:50:00    2011
Name: Year, Length: 541909, dtype: int32
InvoiceDate
2010-12-01 08:26:00    12
2010-12-01 08:26:00    12
2010-12-01 08:26:00    12
2010-12-01 08:26:00    12
2010-12-01 08:26:00    12
                       ..
2011-12-09 12:50:00    12
2011-12-09 12:50:00    12
2011-12-09 12:50:00    12
2011-12-09 12:50:00    12
2011-12-09 12:50:00    12
Name: Month, Length: 541909, dtype: int32

In [74]:
df

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Month,Weekday,Day,Hour,Second
InvoiceDate,,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,2010,12,2,1,8,0
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,2010,12,2,1,8,0
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,2010,12,2,1,8,0
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,2010,12,2,1,8,0
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,2010,12,2,1,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011-12-09 12:50:00,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,0.85,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2.10,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,4.15,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,4.15,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,4.95,12680.0,France,2011,12,4,9,12,0

In [75]:
df_2011 = df.loc['2011']
df_2011

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Month,Weekday,Day,Hour,Second
InvoiceDate,,,,,,,,,,,,,
2011-01-04 10:00:00,539993,22386,JUMBO BAG PINK POLKADOT,10,1.95,13313.0,United Kingdom,2011,1,1,4,10,0
2011-01-04 10:00:00,539993,21499,BLUE POLKADOT WRAP,25,0.42,13313.0,United Kingdom,2011,1,1,4,10,0
2011-01-04 10:00:00,539993,21498,RED RETROSPOT WRAP,25,0.42,13313.0,United Kingdom,2011,1,1,4,10,0
2011-01-04 10:00:00,539993,22379,RECYCLING BAG RETROSPOT,5,2.10,13313.0,United Kingdom,2011,1,1,4,10,0
2011-01-04 10:00:00,539993,20718,RED RETROSPOT SHOPPER BAG,10,1.25,13313.0,United Kingdom,2011,1,1,4,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011-12-09 12:50:00,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,0.85,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2.10,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,4.15,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,4.15,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,4.95,12680.0,France,2011,12,4,9,12,0

In [77]:
df_2011_dec = df.loc['2011-12']
df_2011_dec

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Month,Weekday,Day,Hour,Second
InvoiceDate,,,,,,,,,,,,,
2011-12-01 08:12:00,C579889,23245,SET OF 3 REGENCY CAKE TINS,-8,4.15,13853.0,United Kingdom,2011,12,3,1,8,0
2011-12-01 08:14:00,C579890,84947,ANTIQUE SILVER TEA GLASS ENGRAVED,-1,1.25,15197.0,United Kingdom,2011,12,3,1,8,0
2011-12-01 08:14:00,C579890,23374,RED SPOT PAPER GIFT BAG,-1,0.82,15197.0,United Kingdom,2011,12,3,1,8,0
2011-12-01 08:14:00,C579890,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,-2,0.85,15197.0,United Kingdom,2011,12,3,1,8,0
2011-12-01 08:18:00,C579891,23485,BOTANICAL GARDENS WALL CLOCK,-1,25.00,13644.0,United Kingdom,2011,12,3,1,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011-12-09 12:50:00,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,0.85,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2.10,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,4.15,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,4.15,12680.0,France,2011,12,4,9,12,0
2011-12-09 12:50:00,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,4.95,12680.0,France,2011,12,4,9,12,0

In [78]:
df_dec_range = df.loc['2010-12-01':'2010-12-15']
df_dec_range

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Month,Weekday,Day,Hour,Second
InvoiceDate,,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,2010,12,2,1,8,0
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,2010,12,2,1,8,0
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,2010,12,2,1,8,0
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,2010,12,2,1,8,0
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,2010,12,2,1,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2010-12-15 17:28:00,539075,21154,RED RETROSPOT OVEN GLOVE,4,1.25,17189.0,United Kingdom,2010,12,2,15,17,0
2010-12-15 17:28:00,539075,47559B,TEA TIME OVEN GLOVE,5,1.25,17189.0,United Kingdom,2010,12,2,15,17,0
2010-12-15 17:28:00,539075,21086,SET/6 RED SPOTTY PAPER CUPS,1,0.65,17189.0,United Kingdom,2010,12,2,15,17,0
2010-12-15 17:28:00,539075,22565,FELTCRAFT HAIRBANDS PINK AND WHITE,1,0.85,17189.0,United Kingdom,2010,12,2,15,17,0
2010-12-15 17:28:00,539075,22065,CHRISTMAS PUDDING TRINKET POT,1,1.45,17189.0,United Kingdom,2010,12,2,15,17,0

In [79]:
date_range_new = pd.date_range(start='2024-01-01', end='2024-12-31', freq='D')
date_range_new

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10',
               ...
               '2024-12-22', '2024-12-23', '2024-12-24', '2024-12-25',
               '2024-12-26', '2024-12-27', '2024-12-28', '2024-12-29',
               '2024-12-30', '2024-12-31'],
              dtype='datetime64[us]', length=366, freq='D')

In [ ]:
df_dates = pd.DataFrame(date_range_new, columns=['Date'])